spring:
  application:
    name: mymap
  datasource:
    url: jdbc:postgresql://localhost:5432/mymap
    username: postgres
    password: "1234"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      max-lifetime: 5000
      idle-timeout: 2000
      minimum-idle: 2
      connection-timeout: 20000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  thymeleaf:
    cache: false
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

logging:
  level:
    sql: debug
    org.hibernate.type: trace
    com.mymap: info

jwt:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtzLzFhKD3do8YaWHqJ11EHRIKKdImm/joJKesrI8xCpY4zwOr8v5YB4OdRJ7m7eAWsTLSpgYC9H9/xYu0CypUxwxnulxeGVpqgRt27Tod+vDkxBE5nOFDKmfrz9u8dSg0ANtIlt0mym8xTKqPvGVPOxCn4CpH9MbCXZS1B35UgNcAcDj9Wztt4PEVr4ilOlGmGwx+5orpm0m1wxpoSnf3ZeunnN0nbO2z42scXgtr2/yitKIE/7jsVSbVwrtEbgYl8bu6lBFsASgh9YUlFF4pAFR8wv9ihj5GSn1yg1558sHKld3WFiIUmtVIPePfBLMla2vXe40xTnFCp8xJfWhTwIDAQAB
  private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC3MvMWEoPd2jxhpYeonXUQdEgop0iab+Ogkp6ysjzEKljjPA6vy/lgHg51Enubt4BaxMtKmBgL0f3/Fi7QLKlTHDGe6XF4ZWmqBG3btOh368OTEETmc4UMqZ+vP27x1KDQA20iW3SbKbzFMqo+8ZU87EKfgKkf0xsJdlLUHflSA1wBwOP1bO23g8RWviKU6UaYbDH7miumbSbXDGmhKd/dl66ec3Sds7bPjaxxeC2vb/KK0ogT/uOxVJtXCu0RuBiXxu7qUEWwBKCH1hSUUXikAVHzC/2KGPkZKfXKDXnnywcqV3dYWIhSa1Ug9498EsyVra9d7jTFOcUKnzEl9aFPAgMBAAECggEAFKcqySHnOdtA6WU8PkxvW8kwMAfD40fv6on9As+d6COPXSFyf8EdaQeaa6UHcw5PQGxlMBCmIqxW19YhYENYsiTrNytsKRLjGaa2195fmCgSfAGJMvhyVx4cVtPDkdcoa1WnjQhbGfms7V0BMmgRLLVvQVoY4ZyZX19hMRv79Tx4pztzfel0Q4HidXe9SzVJlP7oRKqSGAST9n6T18Q5cU+WdEJlEFjlvccl8H/TH7t5bfyWTapfK/tQ5pq87Zs64BHGUoelxkpK0eyFb21Pf5bZ4IQCv8I12s1MMltr2Si/eZIjapcdqO41HH7EHGXryP+Hyfb7zdkcuWcDwVaGSQKBgQDu7nOBAL2X/EpwMSwi8VCrSPtaNlpa903Gl51nGiupz3a1vajTzjcWcEjZ+iPHfnNiFLuQSGqgnp4i4FhHiWkpmee5NLv9Qfwo7qdqTRroi2EQU29xQOwUImMHY+fRCi6YFCXeGOU0SkolnNah0xIatL2yS5wMJU94nDFD1aPqDQKBgQDESUVG0dFvaGJR5Na0Z+YCPkuqqRLQa898sTnej6FAaIcOkuTM28zZDtccAQW2WbCzMs/YnR0/YGEiM49mxVH0VyPzqztQ95x8Hk3oA2nVssqX1F/nFhqUDr/CR4fKaLrqMiVeLipKYtiMP2xoc4mxBtsaOqMtNEZIscvp0EHtywKBgQCFZ742GSPC6KrnWY07NWHFQUqWZCKvB8X1TFImbwZSGfQ+JVdOa6V2cds7Wd8AVCo4aTsQpF5ksCu7bWfdCWwePkCTuE3+aglREW+IeuS7UpcvdmaS5Zzq4QhJ6A5XOUgqwZUjHONc/t3HgnqUgDVrk98W3gCTB4IH5a3cIj0TQQKBgCTp9qpT6UQ/aEYoeCxjYcFIP+ivdUdXDyVPGyf88QFw5v1ZqMfSCltDzDaLBqz9fxqkUqxVF9wEXyAUfEKCl2ARR0SbDkOy3W4GMPaSNcQnpKwbF5IY+RShFXUPCL2LJqPGnHpyyidFIZ52iwe1us5dELWFE4z7yMABF+036j4zAoGBANP+uz4c+QLdEzsNQhB3mP2xXtM+jxNIsqwKvMlEHli6ILrb5O5/QbJpaf39TzYQkbnQzMhI0Zq5xlkst/CHBsYj2XFUO1ctZMy/gUBQM5lMXmtndmTyADVpNU/34YPzqyX5QQlACdV4HG1w/UkWfExcRhreYbb0yRd/wZqxMCQt

topis:
  key: "%2F795tRL1pG%2BlgUe4o8OdUD%2BPKmNGCMTDOdbqWa1oxbEpXh8bb8tcSZpeeS8D2VE5dJIoPtbMMXXqxawbVKSaGA%3D%3D"
  other-key: "/795tRL1pG+lgUe4o8OdUD+PKmNGCMTDOdbqWa1oxbEpXh8bb8tcSZpeeS8D2VE5dJIoPtbMMXXqxawbVKSaGA=="
